### ISSUE TITLE
**Success Message for Pull Request and Merging:**

### ISSUE THREAD

**Issue by myHerbDev** [stripe/stripe-python#1419]
**Success Message for Pull Request and Merging:**

---

🎉 **Success!** Your pull request has been successfully merged! 🚀

Thank you for your contribution. Your changes have been integrated into the main branch, and we're excited to see how they improve the project. If you have any further updates or features, feel free to create new pull requests!

Keep up the great work! 🙌

--- 

Feel free to modify it as you like!

_Originally posted by @myHerbDev in https://github.com/stripe/stripe-python/issues/1418#issuecomment-2445759602_
            
```[tasklist]
### Tasks
- [ ] https://github.com/stripe/stripe-python/pull/1417
- [ ] https://github.com/stripe/stripe-python/pull/1329
- [ ] https://github.com/stripe/stripe-python/pull/1411
- [ ] https://github.com/stripe/stripe-python/pull/1416
```

```[tasklist]
### Tasks
- [ ] https://github.com/stripe/stripe-python/pull/1418
- [ ] https://github.com/stripe/stripe-python/issues/1287
- [ ] https://github.com/stripe/stripe-python/issues/770
- [ ] https://github.com/stripe/stripe-python/issues/1333
```
